/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataBookingController;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import controller.JadwalShowController;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author msi-modern
 */
public class AdminJadwal extends javax.swing.JFrame {

    /**
     * Creates new form AdminJadwal
     */
    JadwalShowController jc;
    public AdminJadwal() {
        initComponents();
        jc = new JadwalShowController(this);
        jc.isiTabel();
        DataBookingController dbc = new DataBookingController(this);
        dbc.isiTabel();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableJadwal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        AdminId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AdminHargaReg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButtonAdminInsert = new javax.swing.JButton();
        AdminTanggal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AdminLokasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AdminKuotaReg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ButtonAdminUpdate = new javax.swing.JButton();
        ButtonAdminDelete = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        AdminKuotaVip = new javax.swing.JTextField();
        AdminHargaVip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelBooking = new javax.swing.JTable();
        ButtonBookingDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableJadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableJadwal);

        jLabel2.setText("Id");

        AdminId.setEditable(false);
        AdminId.setText("-");

        jLabel4.setText("Kuota VIP");

        AdminHargaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminHargaRegActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Reg");

        ButtonAdminInsert.setText("Insert");
        ButtonAdminInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminInsertActionPerformed(evt);
            }
        });

        AdminTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminTanggalActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal");

        AdminLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLokasiActionPerformed(evt);
            }
        });

        jLabel6.setText("Lokasi");

        AdminKuotaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminKuotaRegActionPerformed(evt);
            }
        });

        jLabel7.setText("Kuota Reg");

        jLabel8.setText("Harga VIP");

        ButtonAdminUpdate.setText("Update");
        ButtonAdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminUpdateActionPerformed(evt);
            }
        });

        ButtonAdminDelete.setText("Delete");
        ButtonAdminDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminDeleteActionPerformed(evt);
            }
        });

        ButtonKembali.setBackground(new java.awt.Color(255, 0, 0));
        ButtonKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        AdminKuotaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminKuotaVipActionPerformed(evt);
            }
        });

        AdminHargaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminHargaVipActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA PEMESAN");

        TabelBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBookingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelBooking);

        ButtonBookingDelete.setText("Delete");
        ButtonBookingDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBookingDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 333, Short.MAX_VALUE)
                        .addComponent(ButtonBookingDelete)
                        .addGap(279, 279, 279))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonKembali)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(ButtonAdminInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ButtonAdminUpdate)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ButtonAdminDelete))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(AdminId, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(AdminLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(AdminTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(AdminKuotaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(AdminKuotaVip, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(AdminHargaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(AdminHargaVip, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ButtonKembali)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(AdminId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminKuotaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(AdminKuotaVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminHargaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(AdminHargaVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAdminDelete)
                            .addComponent(ButtonAdminUpdate)
                            .addComponent(ButtonAdminInsert))))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonBookingDelete)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminHargaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminHargaRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminHargaRegActionPerformed

    private void ButtonAdminInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminInsertActionPerformed
        // TODO add your handling code here:
        jc.insert();
        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah");
         AdminId.setText("");
    AdminTanggal.setText("");
    AdminLokasi.setText("");
    AdminKuotaReg.setText("");
     AdminKuotaVip.setText("");
    AdminHargaReg.setText("");
    AdminHargaVip.setText("");
    jc.isiTabel();
    }//GEN-LAST:event_ButtonAdminInsertActionPerformed

    private void AdminTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminTanggalActionPerformed

    private void AdminLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLokasiActionPerformed

    private void AdminKuotaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminKuotaRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminKuotaRegActionPerformed

    private void ButtonAdminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminUpdateActionPerformed
        jc.update();
        JOptionPane.showMessageDialog(this, "Data Berhasil diupdate");
         AdminId.setText("");
    AdminTanggal.setText("");
    AdminLokasi.setText("");
    AdminKuotaReg.setText("");
     AdminKuotaVip.setText("");
    AdminHargaReg.setText("");
    AdminHargaVip.setText("");
    jc.isiTabel();
    }//GEN-LAST:event_ButtonAdminUpdateActionPerformed

    private void ButtonAdminDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminDeleteActionPerformed
       jc.delete();
        JOptionPane.showMessageDialog(this, "Data Berhasil dihapus");
         AdminId.setText("");
    AdminTanggal.setText("");
    AdminLokasi.setText("");
    AdminKuotaReg.setText("");
     AdminKuotaVip.setText("");
    AdminHargaReg.setText("");
    AdminHargaVip.setText("");
   jc.isiTabel();
    }//GEN-LAST:event_ButtonAdminDeleteActionPerformed

    private void TableJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableJadwalMouseClicked
       int baris = TableJadwal.getSelectedRow();
   AdminId.setText(TableJadwal.getValueAt(baris, 0).toString());
    AdminTanggal.setText(TableJadwal.getValueAt(baris, 1).toString());
    AdminLokasi.setText(TableJadwal.getValueAt(baris, 2).toString());
    AdminKuotaReg.setText(TableJadwal.getValueAt(baris, 3).toString());
     AdminKuotaVip.setText(TableJadwal.getValueAt(baris, 4).toString());
    AdminHargaReg.setText(TableJadwal.getValueAt(baris, 5).toString());
    AdminHargaVip.setText(TableJadwal.getValueAt(baris, 6).toString());
    }//GEN-LAST:event_TableJadwalMouseClicked

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        JFrame l = new LoginAdmin();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void AdminKuotaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminKuotaVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminKuotaVipActionPerformed

    private void AdminHargaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminHargaVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminHargaVipActionPerformed

    private void ButtonBookingDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBookingDeleteActionPerformed
         DataBookingController dbc = new DataBookingController(this);
        dbc.delete();
        dbc.isiTabel();
    }//GEN-LAST:event_ButtonBookingDeleteActionPerformed

    private void TabelBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBookingMouseClicked
         int baris = TabelBooking.getSelectedRow();
         String BookingId =TabelBooking.getValueAt(baris, 0).toString();
    }//GEN-LAST:event_TabelBookingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminHargaReg;
    private javax.swing.JTextField AdminHargaVip;
    private javax.swing.JTextField AdminId;
    private javax.swing.JTextField AdminKuotaReg;
    private javax.swing.JTextField AdminKuotaVip;
    private javax.swing.JTextField AdminLokasi;
    private javax.swing.JTextField AdminTanggal;
    private javax.swing.JButton ButtonAdminDelete;
    private javax.swing.JButton ButtonAdminInsert;
    private javax.swing.JButton ButtonAdminUpdate;
    private javax.swing.JButton ButtonBookingDelete;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JTable TabelBooking;
    private javax.swing.JTable TableJadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

   
    public JTextField getAdminId() {
        return AdminId;
    }

    public void setAdminId(JTextField AdminId) {
        this.AdminId = AdminId;
    }

   
    public JTextField getAdminReg() {
        return AdminHargaReg;
    }

    public void setAdminReg(JTextField AdminReg) {
        this.AdminHargaReg = AdminReg;
    }

    public JTextField getAdminShow() {
        return AdminKuotaVip;
    }

    public void setAdminShow(JTextField AdminShow) {
        this.AdminKuotaVip = AdminShow;
    }

    public JTextField getAdminVip() {
        return AdminHargaVip;
    }

    public void setAdminVip(JTextField AdminVip) {
        this.AdminHargaVip = AdminVip;
    }

    public JButton getButtonAdminDelete() {
        return ButtonAdminDelete;
    }

    public void setButtonAdminDelete(JButton ButtonAdminDelete) {
        this.ButtonAdminDelete = ButtonAdminDelete;
    }

    public JButton getButtonAdminInsert() {
        return ButtonAdminInsert;
    }

    public void setButtonAdminInsert(JButton ButtonAdminInsert) {
        this.ButtonAdminInsert = ButtonAdminInsert;
    }

    public JButton getButtonAdminUpdate() {
        return ButtonAdminUpdate;
    }

    public void setButtonAdminUpdate(JButton ButtonAdminUpdate) {
        this.ButtonAdminUpdate = ButtonAdminUpdate;
    }

    public JTable getTableJadwal() {
        return TableJadwal;
    }

    public void setTableJadwal(JTable TableJadwal) {
        this.TableJadwal = TableJadwal;
    }

    public JTextField getAdminHargaReg() {
        return AdminHargaReg;
    }

    public void setAdminHargaReg(JTextField AdminHargaReg) {
        this.AdminHargaReg = AdminHargaReg;
    }

    public JTextField getAdminHargaVip() {
        return AdminHargaVip;
    }

    public void setAdminHargaVip(JTextField AdminHargaVip) {
        this.AdminHargaVip = AdminHargaVip;
    }

    public JTextField getAdminKuotaReg() {
        return AdminKuotaReg;
    }

    public void setAdminKuotaReg(JTextField AdminKuotaReg) {
        this.AdminKuotaReg = AdminKuotaReg;
    }

    public JTextField getAdminKuotaVip() {
        return AdminKuotaVip;
    }

    public void setAdminKuotaVip(JTextField AdminKuotaVip) {
        this.AdminKuotaVip = AdminKuotaVip;
    }

    public JTextField getAdminLokasi() {
        return AdminLokasi;
    }

    public void setAdminLokasi(JTextField AdminLokasi) {
        this.AdminLokasi = AdminLokasi;
    }

    public JTextField getAdminTanggal() {
        return AdminTanggal;
    }

    public void setAdminTanggal(JTextField AdminTanggal) {
        this.AdminTanggal = AdminTanggal;
    }

    public JTable getTabelBooking() {
        return TabelBooking;
    }

    public void setTabelBooking(JTable TabelBooking) {
        this.TabelBooking = TabelBooking;
    }
    
    
    
}
