/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import controller.MainViewController;
import model.BookingConfirmation;
import kalkulator.Kalkulator;

/**
 *
 * @author msi-modern
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    MainViewController mv;
    ConfirmWindow cf;
    public MainView() {
        initComponents();
        mv = new MainViewController(this);
        mv.isiDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuJadwal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnJadwal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HargaReguler = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SisaReguler = new javax.swing.JLabel();
        SpinReguler = new javax.swing.JSpinner();
        sisaRegInv = new javax.swing.JLabel();
        hargaReg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        HargaVip = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SisaVip = new javax.swing.JLabel();
        SpinVip = new javax.swing.JSpinner();
        sisaVipInv = new javax.swing.JLabel();
        hargaVipStatic = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        InNama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        InEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InNoHp = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        TxtTot = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnPesan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JLabel();
        TxtTax = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pilih Jadwal Show");

        BtnJadwal.setText("Pilih");
        BtnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MenuJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuJadwal))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pilih Kursi");

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel3.setText("Reguler");

        HargaReguler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HargaReguler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HargaReguler.setText("Harga");

        jLabel6.setText("Sisa:");

        SisaReguler.setText("-");

        SpinReguler.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinRegulerStateChanged(evt);
            }
        });

        sisaRegInv.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        sisaRegInv.setForeground(getBackground());
        sisaRegInv.setText("jLabel4");

        hargaReg.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        hargaReg.setForeground(getBackground());
        hargaReg.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HargaReguler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(sisaRegInv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SisaReguler)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SpinReguler, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sisaRegInv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HargaReguler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SisaReguler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hargaReg)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SpinReguler, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VIP");

        HargaVip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HargaVip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HargaVip.setText("Harga");

        jLabel8.setText("Sisa:");

        SisaVip.setText("-");

        SpinVip.setRequestFocusEnabled(false);
        SpinVip.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinVipStateChanged(evt);
            }
        });

        sisaVipInv.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        sisaVipInv.setForeground(javax.swing.UIManager.getDefaults().getColor("window"));
        sisaVipInv.setText("jLabel4");

        hargaVipStatic.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        hargaVipStatic.setForeground(getBackground());
        hargaVipStatic.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HargaVip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sisaVipInv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(SpinVip, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hargaVipStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SisaVip)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HargaVip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SisaVip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sisaVipInv)
                            .addComponent(hargaVipStatic))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SpinVip, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(412, 197));

        jLabel5.setText("Nama");

        InNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNamaActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        InEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InEmailActionPerformed(evt);
            }
        });

        jLabel12.setText("Nomor HP");

        InNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNoHpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(InEmail)
                    .addComponent(InNama)
                    .addComponent(InNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        TxtTot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TxtTot.setText("tot");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Grand Total:");

        BtnPesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPesan.setText("PESAN");
        BtnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesanActionPerformed(evt);
            }
        });

        jLabel14.setText("Tax (11%)");

        jLabel15.setText("Total");

        TxtTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TxtTotal.setText("0");

        TxtTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TxtTax.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(BtnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(TxtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Data Diri Pemesan");

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNoHpActionPerformed

    private void InEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InEmailActionPerformed

    private void InNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNamaActionPerformed

    private void BtnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesanActionPerformed
        // TODO add your handling code here:
        ErrorBox err;
        if("".equals(getInNama().getText()) ||
           "".equals(getInEmail().getText()) ||
           "".equals(getInNoHp().getText())
        ) {
            err = new ErrorBox("kosong");
            err.setVisible(true);
            err.setLocationRelativeTo(null);
        } else if (Integer.parseInt(getSpinVip().getValue().toString()) < 0 ||
                   Integer.parseInt(getSpinReguler().getValue().toString()) < 0
        )  {
            err = new ErrorBox("invalid");
            err.setVisible(true);
            err.setLocationRelativeTo(null);
        } else {
//            System.out.println("kontol");
            BookingConfirmation bc = new BookingConfirmation();
            Kalkulator k = new Kalkulator();
            bc.setNama(getInNama().getText());
            bc.setEmail(getInEmail().getText());
            bc.setNoHp(getInNoHp().getText());
            bc.setTanggal(getMenuJadwal().getSelectedItem().toString());
            bc.setIdJadwalShow(getMenuJadwal().getSelectedIndex() + 1);
            bc.setJmlReguler(Integer.parseInt(getSpinReguler().getValue().toString()));
            bc.setJmlVip(Integer.parseInt(getSpinVip().getValue().toString()));
            bc.setTotal(k.hitungJumlah(Integer.parseInt(getHargaVipStatic().getText()), bc.getJmlVip()) + k.hitungJumlah(Integer.parseInt(getHargaReg().getText()), bc.getJmlReguler()));
            bc.setTax((int) k.hitungPajak(bc.getTotal()));
            bc.setGtot((int) k.hitungTotal(bc.getTotal()));
            System.out.println(bc.getNama());
            cf = new ConfirmWindow(bc);
            cf.setVisible(true);
            cf.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_BtnPesanActionPerformed

    private void BtnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJadwalActionPerformed
        // TODO add your handling code here:
        JComboBox<String> dd = this.getMenuJadwal();
        int id = dd.getSelectedIndex();
        mv.isiKuota(id);
        mv.isiHarga(id);
    }//GEN-LAST:event_BtnJadwalActionPerformed

    private void SpinRegulerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinRegulerStateChanged
        // TODO add your handling code here:
        JLabel sisaFix = this.getSisaRegInv();
        JLabel sisa = this.getSisaReguler();
        JSpinner s = this.getSpinReguler();
        mv.ubahKuota(sisaFix, sisa, s);
        mv.updateBayar();
    }//GEN-LAST:event_SpinRegulerStateChanged

    private void SpinVipStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinVipStateChanged
        // TODO add your handling code here:
        JLabel sisaFix = this.getSisaVipInv();
        JLabel sisa = this.getSisaVip();
        JSpinner s = this.getSpinVip();
        mv.ubahKuota(sisaFix, sisa, s);
        mv.updateBayar();
    }//GEN-LAST:event_SpinVipStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnJadwal;
    private javax.swing.JButton BtnPesan;
    private javax.swing.JLabel HargaReguler;
    private javax.swing.JLabel HargaVip;
    private javax.swing.JLabel HargaVip1;
    private javax.swing.JTextField InEmail;
    private javax.swing.JTextField InNama;
    private javax.swing.JTextField InNoHp;
    private javax.swing.JComboBox<String> MenuJadwal;
    private javax.swing.JLabel SisaReguler;
    private javax.swing.JLabel SisaVip;
    private javax.swing.JLabel SisaVip1;
    private javax.swing.JSpinner SpinReguler;
    private javax.swing.JSpinner SpinVip;
    private javax.swing.JSpinner SpinVip1;
    private javax.swing.JLabel TxtTax;
    private javax.swing.JLabel TxtTot;
    private javax.swing.JLabel TxtTotal;
    private javax.swing.JLabel hargaReg;
    private javax.swing.JLabel hargaVipStatic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel sisaRegInv;
    private javax.swing.JLabel sisaVipInv;
    // End of variables declaration//GEN-END:variables

    public JLabel getHargaReguler() {
        return HargaReguler;
    }

    public void setHargaReguler(JLabel HargaReguler) {
        this.HargaReguler = HargaReguler;
    }

    public JLabel getHargaVip() {
        return HargaVip;
    }

    public void setHargaVip(JLabel HargaVip) {
        this.HargaVip = HargaVip;
    }

    public JTextField getInEmail() {
        return InEmail;
    }

    public void setInEmail(JTextField InEmail) {
        this.InEmail = InEmail;
    }

    public JTextField getInNama() {
        return InNama;
    }

    public void setInNama(JTextField InNama) {
        this.InNama = InNama;
    }

    public JTextField getInNoHp() {
        return InNoHp;
    }

    public void setInNoHp(JTextField InNoHp) {
        this.InNoHp = InNoHp;
    }

    public JComboBox<String> getMenuJadwal() {
        return MenuJadwal;
    }

    public void setMenuJadwal(JComboBox<String> MenuJadwal) {
        this.MenuJadwal = MenuJadwal;
    }

    public JLabel getSisaReguler() {
        return SisaReguler;
    }

    public void setSisaReguler(JLabel SisaReguler) {
        this.SisaReguler = SisaReguler;
    }

    public JLabel getSisaVip() {
        return SisaVip;
    }

    public void setSisaVip(JLabel SisaVip) {
        this.SisaVip = SisaVip;
    }

    public JSpinner getSpinReguler() {
        return SpinReguler;
    }

    public void setSpinReguler(JSpinner SpinReguler) {
        this.SpinReguler = SpinReguler;
    }

    public JSpinner getSpinVip() {
        return SpinVip;
    }

    public void setSpinVip(JSpinner SpinVip) {
        this.SpinVip = SpinVip;
    }

    public JLabel getTxtTax() {
        return TxtTax;
    }

    public void setTxtTax(JLabel TxtTax) {
        this.TxtTax = TxtTax;
    }

    public JLabel getTxtTotal() {
        return TxtTotal;
    }

    public void setTxtTotal(JLabel TxtTotal) {
        this.TxtTotal = TxtTotal;
    }

    public JLabel getSisaRegInv() {
        return sisaRegInv;
    }

    public void setSisaRegInv(JLabel sisaRegInv) {
        this.sisaRegInv = sisaRegInv;
    }

    public JLabel getSisaVipInv() {
        return sisaVipInv;
    }

    public void setSisaVipInv(JLabel sisaVipInv) {
        this.sisaVipInv = sisaVipInv;
    }

    public JLabel getHargaReg() {
        return hargaReg;
    }

    public void setHargaReg(JLabel hargaReg) {
        this.hargaReg = hargaReg;
    }

    public JLabel getHargaVipStatic() {
        return hargaVipStatic;
    }

    public void setHargaVipStatic(JLabel hargaVipStatic) {
        this.hargaVipStatic = hargaVipStatic;
    }    

    public JLabel getTxtTot() {
        return TxtTot;
    }

    public void setTxtTot(JLabel TxtTot) {
        this.TxtTot = TxtTot;
    }
}
